# Generated by Django 2.2.2 on 2019-06-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190619_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='URL'),
        ),
    ]
